version: "3.4"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - postgresql-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql-db:5432/sonar
      SONAR_JDBC_USERNAME: ${POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    restart: always
    networks:
      - sonarnet

  postgresql-db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    restart: always
    networks:
      - sonarnet

  reverse_proxy:
      container_name: reverse_proxy
      depends_on:
        - sonarqube
      image: nginx
      networks:
        - sonarnet
      ports:
        - "80:80"
        - "443:443"
      restart: always
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - /home/ubuntu/.certbot/config/live/sonarqube.headydev.io/fullchain.pem:/etc/ssl/certs/fullchain.pem
        - /home/ubuntu/.certbot/config/live/sonarqube.headydev.io/privkey.pem:/etc/ssl/private/privkey.pem

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: